### ISSUE TITLE
ShinyProxy-On Kubernetes Error 

### ISSUE THREAD

**Issue by jino-varghese** [openanalytics/shinyproxy-config-examples#25]
On Kubernetes, Shiny Proxy fails to launch the docker image which I build manually.  but the same image run successfully with docker-compose. 

The page shows :- 

Error
Status code: 500

Message: Failed to start container

Stack Trace:
eu.openanalytics.containerproxy.ContainerProxyException: Failed to start container
at eu.openanalytics.containerproxy.backend.AbstractContainerBackend.startProxy(AbstractContainerBackend.java:110)
at eu.openanalytics.containerproxy.service.ProxyService.startProxy(ProxyService.java:213)
at eu.openanalytics.shinyproxy.controllers.AppController.getOrStart(AppController.java:89)
at eu.openanalytics.shinyproxy.controllers.AppController.startApp(AppController.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:870)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:776)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:881)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

Could you help to fix this.

**Comment by corey-dawson** [comment]
I have the same issue running containerized shinyproxy in kubernetes. I have gotten this to work by using sidecar. I was under the impression 2.4.0 and above didnt need side car

**Comment by jino-varghese** [comment]
Thank you. I have tried this, unfortunately i get  same error message  as above mentioned. 
Attached my execution as well as the changes i made in the file.  
could you take a look and help me where it went wrong. 
Thank you so much  for your help. 

[Shinyproxy_Kubernetes.txt](https://github.com/openanalytics/shinyproxy-config-examples/files/6378711/Shinyproxy_Kubernetes.txt)

**Comment by LEDfan** [comment]
Hi @jino-varghese 

First of all, I see from your txt file that you are trying to run ShinyProxy 2.1.0, currently we are at ShinyProxy 2.5.0 and there should be no reason to use such a old version. 
Furthermore, I advise you to use our official Docker images, since we follow best practices on building these images. See https://github.com/openanalytics/shinyproxy-config-examples/tree/master/03-containerized-kubernetes for more information.  Also have a look at https://github.com/openanalytics/shinyproxy-config-examples/tree/master/03-containerized-kubernetes#notes-on-the-configuration

If you still get an error, please provide the full stack trace, so that we can check what's going on.

**Comment by jino-varghese** [comment]
Thank you for your update. i face the same issue and i attach all relevant information, let me know is there anything that i need to pull for analysis. 

[Shiny_proxy-Kube-Error.zip](https://github.com/openanalytics/shinyproxy-config-examples/files/6395097/Shiny_proxy-Kube-Error.zip)

**Comment by LEDfan** [comment]
Thank you for the extensive information on your setup! I think you are missing one step in your setup of the custom image: you must upload the image to some Docker registry, such that Kubernetes can pull the image. Either you upload it to a public registry, a private registry or you make sure that the image is available on the Kubernetes nodes. I think you did this with the `shiny-example`, but you must also do it for the `shiny-applications` image. 

As a tip when ShinyProxy gives the `container did not response in time` error message, you can look on Kubernetes level waht's going wrong. E.g. using:

```
kubectl get pods -n shiny-proxy
kubectl describe pod/sp-pod-<some_id> 
```
At the event of this command you will get a list with events. I think one of them will be that Kubernetes cannot pull the image.

**Comment by jino-varghese** [comment]
Thank you so much for your great help. 
I have a shiny app image that pushed to the public repo (https://hub.docker.com/)  and my private repo. (GitLab)
then I pull both images in my Kube node server, then specify it in the application.yaml file. 
it works well for the public repo image but not for the private repo image. 
I was wondering why the same image from on private container repo does not work?

**Comment by LEDfan** [comment]
Hi

Unfortunately I currently don't have any idea what could be wrong. It could be that ShinyProxy or Kube is trying to pull the image (even though it's available) and that this action is failing. If this is the case, Kube will at some events to the pod, so I can only advice to have a look at the pod (using the commands above).

**Comment by jino-varghese** [comment]
Thank you. This is has ben fixed by deploy the shiny other app along with Shiny proxy.

**Comment by kabbz** [comment]
I'am having the same problem, it's working only if deploy the shiny other app along with Shiny proxy but is not a generic solution, I can deploy using ci cd, because ill need to change the tag each time i change the code and deploy two  images and then two pod on kuberrnetes @LEDfan
