### ISSUE TITLE
Example of using external-url

### ISSUE THREAD

**Issue by danielloader** [openanalytics/shinyproxy-config-examples#41]
Excitedly been watching the released notifications for 3.1.0 and this feature has turned up, but I don't know how to use it, so a simple example would be appreciated!

Thanks

**Comment by LEDfan** [comment]
Hi, I just added an example to the documentation: https://shinyproxy.io/documentation/configuration/#external-url
Hope this helps!

**Comment by danielloader** [comment]
I've tried this and I get this error:

```
eu.openanalytics.containerproxy.ProxyFailedToStartException: Container failed to start
	at eu.openanalytics.containerproxy.service.ProxyService.prepareProxyForStart(ProxyService.java:458) ~[containerproxy-1.1.0.jar!/:1.1.0]
	at eu.openanalytics.containerproxy.service.ProxyService.startOrResumeProxy(ProxyService.java:466)
	at eu.openanalytics.containerproxy.service.ProxyService.lambda$startProxy$7(ProxyService.java:293)
	at eu.openanalytics.containerproxy.service.ProxyService.lambda$action$14(ProxyService.java:638)
	... 5 frames excluded
Caused by: java.lang.IllegalStateException: This is an external app and cannot be started
	at eu.openanalytics.shinyproxy.external.ExternalAppSpecExtension.firstResolve(ExternalAppSpecExtension.java:49) ~[!/:3.1.0]
	at eu.openanalytics.shinyproxy.external.ExternalAppSpecExtension.firstResolve(ExternalAppSpecExtension.java:35)
	at eu.openanalytics.containerproxy.model.spec.ProxySpec.lambda$firstResolve$0(ProxySpec.java:135) ~[containerproxy-1.1.0.jar!/:1.1.0]
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[na:na]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at eu.openanalytics.containerproxy.model.spec.ProxySpec.firstResolve(ProxySpec.java:133) ~[containerproxy-1.1.0.jar!/:1.1.0]
	at eu.openanalytics.containerproxy.service.ProxyService.prepareProxyForStart(ProxyService.java:433)
	... 8 common frames omitted

```

With the relevant config:

``` yaml
application:
  proxy:
    specs:
      - id: basic-external-url
        display-name: Basic External URL
        description: Example description
        external-url: https://shinyproxy.io
        access-groups:
        - admins
```
