### ISSUE TITLE
Application run failed (standalone-docker-engine)

### ISSUE THREAD

**Issue by halljonas** [openanalytics/shinyproxy-config-examples#8]
I tried to run the shinyproxy example in the [standalone version](https://github.com/openanalytics/shinyproxy-config-examples/tree/master/01-standalone-docker-engine). It failed with the error message: 
> [main] o.s.boot.SpringApplication: Application run failed

I'm running docker toolbox in Windows 8 (but also tried with linux mint). I first tried with the most recent shinyproxy version, then with shinyproxy-2.0.0, as mentioned in the example.

Here's my java version
> $ java -version
> java version "1.8.0_181"
> Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
> Java HotSpot(TM) Client VM (build 25.181-b13, mixed mode)

Also 
> $ docker run hello-world

works fine, so docker deamon is running.

What am I not seeing here?

**Comment by graue70** [comment]
Hello,
I seem to have the same problem with Linux Mint 18.2. I followed the steps in the example 01 and get this error message:

```
2018-11-21 16:33:59.098 ERROR 4601 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ldapContextSource' defined in class path resource [org/springframework/boot/autoconfigure/ldap/LdapAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.ldap.core.ContextSource]: Factory method 'ldapContextSource' threw exception; nested exception is java.lang.IllegalAccessError: class org.springframework.ldap.core.support.AbstractContextSource (in unnamed module @0x2cac4385) cannot access class com.sun.jndi.ldap.LdapCtxFactory (in module java.naming) because module java.naming does not export com.sun.jndi.ldap to unnamed module @0x2cac4385
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:587) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) ~[spring-boot-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388) ~[spring-boot-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) ~[spring-boot-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at eu.openanalytics.containerproxy.ContainerProxyApplication.main(ContainerProxyApplication.java:67) [containerproxy-0.6.0.jar!/:0.6.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:531) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [shinyproxy-2.0.5.jar:2.0.5]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [shinyproxy-2.0.5.jar:2.0.5]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [shinyproxy-2.0.5.jar:2.0.5]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [shinyproxy-2.0.5.jar:2.0.5]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.ldap.core.ContextSource]: Factory method 'ldapContextSource' threw exception; nested exception is java.lang.IllegalAccessError: class org.springframework.ldap.core.support.AbstractContextSource (in unnamed module @0x2cac4385) cannot access class com.sun.jndi.ldap.LdapCtxFactory (in module java.naming) because module java.naming does not export com.sun.jndi.ldap to unnamed module @0x2cac4385
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	... 24 common frames omitted
Caused by: java.lang.IllegalAccessError: class org.springframework.ldap.core.support.AbstractContextSource (in unnamed module @0x2cac4385) cannot access class com.sun.jndi.ldap.LdapCtxFactory (in module java.naming) because module java.naming does not export com.sun.jndi.ldap to unnamed module @0x2cac4385
	at org.springframework.ldap.core.support.AbstractContextSource.<clinit>(AbstractContextSource.java:77) ~[spring-ldap-core-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
	at org.springframework.boot.autoconfigure.ldap.LdapAutoConfiguration.ldapContextSource(LdapAutoConfiguration.java:54) ~[spring-boot-autoconfigure-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.boot.autoconfigure.ldap.LdapAutoConfiguration$$EnhancerBySpringCGLIB$$71946428.CGLIB$ldapContextSource$0(<generated>) ~[spring-boot-autoconfigure-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.boot.autoconfigure.ldap.LdapAutoConfiguration$$EnhancerBySpringCGLIB$$71946428$$FastClassBySpringCGLIB$$6e5e2c4d.invoke(<generated>) ~[spring-boot-autoconfigure-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361) ~[spring-context-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.boot.autoconfigure.ldap.LdapAutoConfiguration$$EnhancerBySpringCGLIB$$71946428.ldapContextSource(<generated>) ~[spring-boot-autoconfigure-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:531) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	... 25 common frames omitted
```

```
$ java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```

```
$ docker -v
Docker version 18.09.0, build 4d60db4
```

```
shinyproxy-2.0.5.jar
```

**Comment by LEDfan** [comment]
Hi

This is quite an old issue and the mentioned problems should be fixed in the recent releases of ShinyProxy.
Therefore I'm going to close this issue, but feel free to open a new issue if you still have any problem with a recent version of ShinyProxy.
